name: Cypress API Tests

on: [push, pull_request]

jobs:
  api-tests:
    name: ${{ matrix.env }} Environment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [dev, prod]

    services:
      api-service:
        image: ghcr.io/danielsilva-loanpro/sdet-interview-challenge:latest
        ports:
          - 3000:3000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          env: environment=${{ matrix.env }}
          
      - name: Generate Final HTML Report
        if: always()
        run: npm run generate:report

      - name: Upload Testing Report Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testing-report-${{ matrix.env }}
          path: |
            cypress/final-report
            cypress/screenshots
            cypress/videos